# Generated by Django 3.0.6 on 2020-05-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Catégorie')),
            ],
            options={
                'verbose_name_plural': 'Catégories',
            },
        ),
    ]
