# Generated by Django 3.0.7 on 2020-07-04 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Catégorie')),
            ],
            options={
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Nutriment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saturated_fat_quantity', models.FloatField(default=0, verbose_name='Acides gras saturés')),
                ('salt_quantity', models.FloatField(default=0, verbose_name='Sel')),
                ('sugars_quantity', models.FloatField(default=0, verbose_name='Sucre')),
                ('fat_quantity', models.FloatField(default=0, verbose_name='Matières Grasses/Lipides')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('brand', models.CharField(max_length=100, verbose_name='Marque')),
                ('nutrition_grade', models.CharField(max_length=1, verbose_name='Nutri-Score')),
                ('ingredients', models.TextField(verbose_name='Liste des ingrédients')),
                ('url', models.URLField(verbose_name='Lien vers Open Food Facts')),
                ('small_image_url', models.URLField(verbose_name='URL small image')),
                ('large_image_url', models.URLField(verbose_name='URL large image')),
                ('categories', models.ManyToManyField(related_name='Products', to='general.Category')),
                ('nutriment', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='nutriment', to='general.Nutriment')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituted', to='general.Product')),
                ('substitute_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute', to='general.Product')),
            ],
            options={
                'verbose_name_plural': 'Favorites User',
            },
        ),
    ]
