# Generated by Django 3.0.6 on 2020-05-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_nutriment'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutriment',
            name='fat_quantity',
            field=models.FloatField(default=0, verbose_name='Matières Grasses/Lipides'),
        ),
        migrations.AddField(
            model_name='nutriment',
            name='salt_quantity',
            field=models.FloatField(default=0, verbose_name='Sel'),
        ),
        migrations.AddField(
            model_name='nutriment',
            name='saturated_fat_quantity',
            field=models.FloatField(default=0, verbose_name='Acides gras saturés'),
        ),
        migrations.AddField(
            model_name='nutriment',
            name='sugars_quantity',
            field=models.FloatField(default=0, verbose_name='Sucre'),
        ),
    ]
