# Generated by Django 3.0.6 on 2020-05-22 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20200522_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('brand', models.CharField(max_length=100, verbose_name='Marque')),
                ('nutrition_grade', models.CharField(max_length=1, verbose_name='Nutri-Score')),
                ('ingredients', models.TextField(verbose_name='Liste des ingrédients')),
                ('url', models.URLField(verbose_name='Lien vers Open Food Facts')),
                ('small_image_url', models.URLField(verbose_name='URL small image')),
                ('large_image_url', models.URLField(verbose_name='URL large image')),
                ('categories', models.ManyToManyField(related_name='Products', to='general.Category')),
                ('nutriment', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='nutriment', to='general.Nutriment')),
            ],
        ),
    ]
